---
title: "week01-questions"
output: html_document
date: "2025-04-03"
---

**What is your prior experience in this discipline?**\
I have experience using bash/shell scripting and HPC computing from previous research and from undergraduate coursework (but that was years ago)! I also have some experience in processing genetic data - programs like MEGA, Geneious, smaller programs for downstream analysis, etc. That being said, some of my experience is either spotty, minimal, or was long enough ago that I'm rusty.

**What do you hope to get out of this class?**\
Looking for an overall refresher and reinforcement on bioinformatics processes is the main goal, as I'm in the midst of my own MS project's bioinformatics pipeline right now. Looking forward to the project aspect - not only will that help me solidify all of the topics we cover in class and through assignments, but synthesize it using my own data! So leaving the class with something tangible related to my current research will be great.

**This class is strongly rooted in an independent project related to genomic analyses. What specific project do you have in mind? If you do not have any data or preference, data can be provided / acquired. If you do not have a specific project, what approach would you like to master as part of this class?**\
I have RAD-seq data from several hundred individuals of three different rockfish species. Part of it is still raw sequences (processing as we speak), but a couple hundred of those have already been processed, as they were part of a previous research project (not mine). My project is based on population structure and hybridization, so I could pick a specific analysis to use as my focal point as long as it fits in the bounds of the project goals! We often use PCAs and Structure plots for population structure analysis & visualization, so that's one option, but I would love to know how specific and/or extensive the project needs to be and can decide from there.

**What are two things you found most useful from the reading?**\
1. I like the mention of using assert functions/stopifnot as that's one piece of the defensive programming puzzle I don't see talked about very often. I don't think many of us incorporate them, so where it is possible, it should absolutely be used! The larger picture - programs having the ability to spit out a result regardless of if it makes sense or has an error that isn't noticed - really begs for more checks to be built into our processes.\
2. One thing that stuck out to me in the documentation section of Chapter 2 - besides the helpful reaffirmation of how important it is for reproducibility that things are well documented - is the specific points to document where, how, and what version of data was downloaded; given how fast things are changing these days with data availability, it feels more important now than ever to ensure that information is recorded clearly. I've definitely been guilty in the past of thinking "I'll get to it later" when it comes to fleshing out my documentation for certain things - time to break that habit!
